### ISSUE TITLE
Error occurred while disabling WildLoaders

### ISSUE THREAD

**Issue by andrewkm** [BG-Software-LLC/WildLoaders#100]
### Minecraft's Version

Paper 1.20.4 Build 497

### Plugin's Version

v2024.1-b25

### Describe the bug

```
[18:28:55] [Server thread/INFO]: [WildLoaders] Disabling WildLoaders v2024.1-b25
[18:28:55] [Server thread/ERROR]: Error occurred while disabling WildLoaders v2024.1-b25
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.runDelayed(FoliaGlobalRegionScheduler.java:65) ~[paper-1.20.6.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.run(FoliaGlobalRegionScheduler.java:53) ~[paper-1.20.6.jar:?]
	at WildLoaders-2024.1-b25.jar/com.bgsoftware.wildloaders.scheduler.FoliaSchedulerImplementation.scheduleTask(FoliaSchedulerImplementation.java:50) ~[WildLoaders-2024.1-b25.jar:?]
	at WildLoaders-2024.1-b25.jar/com.bgsoftware.wildloaders.scheduler.Scheduler.runTask(Scheduler.java:48) ~[WildLoaders-2024.1-b25.jar:?]
	at WildLoaders-2024.1-b25.jar/com.bgsoftware.wildloaders.scheduler.Scheduler.runTask(Scheduler.java:76) ~[WildLoaders-2024.1-b25.jar:?]
	at WildLoaders-2024.1-b25.jar/com.bgsoftware.wildloaders.nms.v1_20_4.NMSAdapterImpl.removeLoader(NMSAdapterImpl.java:145) ~[WildLoaders-2024.1-b25.jar:?]
	at WildLoaders-2024.1-b25.jar/com.bgsoftware.wildloaders.handlers.LoadersHandler.lambda$removeChunkLoaders$6(LoadersHandler.java:198) ~[WildLoaders-2024.1-b25.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4785) ~[?:?]
	at WildLoaders-2024.1-b25.jar/com.bgsoftware.wildloaders.handlers.LoadersHandler.removeChunkLoaders(LoadersHandler.java:198) ~[WildLoaders-2024.1-b25.jar:?]
	at WildLoaders-2024.1-b25.jar/com.bgsoftware.wildloaders.WildLoadersPlugin.onDisable(WildLoadersPlugin.java:97) ~[WildLoaders-2024.1-b25.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:540) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:573) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:978) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:842) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### To Reproduce

Stop server, happens occasionally.

**Comment by JACKKY04** [comment]
I'm getting this, any solution?

**Comment by andrewkm** [comment]
Still getting this on the latest WildLoaders and 1.21.4. @OmerBenGera 

```
[12:42:25] [Server thread/INFO]: [WildLoaders] Disabling WildLoaders v2024.4-b47
[12:42:25] [Server thread/ERROR]: Error occurred while disabling WildLoaders v2024.4-b47
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.runDelayed(FoliaGlobalRegionScheduler.java:65) ~[paper-1.21.4.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.run(FoliaGlobalRegionScheduler.java:53) ~[paper-1.21.4.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FallbackRegionScheduler.run(FallbackRegionScheduler.java:18) ~[paper-1.21.4.jar:?]
	at WildLoaders-2024.4-b47.jar/com.bgsoftware.wildloaders.scheduler.FoliaSchedulerImplementation.scheduleTask(FoliaSchedulerImplementation.java:28) ~[WildLoaders-2024.4-b47.jar:?]
	at WildLoaders-2024.4-b47.jar/com.bgsoftware.wildloaders.scheduler.Scheduler.runTask(Scheduler.java:40) ~[WildLoaders-2024.4-b47.jar:?]
	at WildLoaders-2024.4-b47.jar/com.bgsoftware.wildloaders.scheduler.Scheduler.runTask(Scheduler.java:68) ~[WildLoaders-2024.4-b47.jar:?]
	at WildLoaders-2024.4-b47.jar/com.bgsoftware.wildloaders.nms.v1_21_4.EntityHologram.removeHologram(EntityHologram.java:57) ~[WildLoaders-2024.4-b47.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597) ~[?:?]
	at WildLoaders-2024.4-b47.jar/com.bgsoftware.wildloaders.nms.v1_21_4.NMSAdapterImpl.removeLoader(NMSAdapterImpl.java:141) ~[WildLoaders-2024.4-b47.jar:?]
	at WildLoaders-2024.4-b47.jar/com.bgsoftware.wildloaders.handlers.LoadersHandler.lambda$removeChunkLoaders$6(LoadersHandler.java:200) ~[WildLoaders-2024.4-b47.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4788) ~[?:?]
	at WildLoaders-2024.4-b47.jar/com.bgsoftware.wildloaders.handlers.LoadersHandler.removeChunkLoaders(LoadersHandler.java:199) ~[WildLoaders-2024.4-b47.jar:?]
	at WildLoaders-2024.4-b47.jar/com.bgsoftware.wildloaders.WildLoadersPlugin.onDisable(WildLoadersPlugin.java:98) ~[WildLoaders-2024.4-b47.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:624) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1061) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:793) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:1025) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:92) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at org.spigotmc.RestartCommand.restart(RestartCommand.java:61) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at LiquidSafe.jar/com.ecocitycraft.liquidcore.commands.templates.QuickRestartTemplate.restart(QuickRestartTemplate.java:70) ~[LiquidSafe.jar:?]
	at LiquidSafe.jar/com.ecocitycraft.liquidcore.paper.PaperQuickRestartTemplate.lambda$run$0(PaperQuickRestartTemplate.java:25) ~[LiquidSafe.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1805) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1666) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1331) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed
