### ISSUE TITLE
No enchantments for Bedrock players

### ISSUE THREAD

**Issue by JustSimplyGaming** [BG-Software-LLC/WildLoaders#104]
### Minecraft's Version

1.21

### Plugin's Version

SuperiorSkyblock2-2024.1-b259

### Describe the bug

After the installation of this Plugin, every Bedrock players dosnt have the possibility to break blocks and all enchantments are removed.
I know that its not officialsupported for Bedrock, but why are the Enchantments blocked and the breaking of blocks is disabled?

For Java the Plugin works great!

### To Reproduce

Set up Geyser Server and use the Plugin

**Comment by JustSimplyGaming** [comment]
Ah, not even the Java players cant break blocks in the normal world.
On the Island it works as it should

**Comment by JustSimplyGaming** [comment]
The Log for Bedrock enchantments.

[09:12:55 WARN]: java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.item.enchantment.Enchantment.bedrockEnchantment()" because "enchantment" is null
[09:12:55 WARN]:        at Geyser-Spigot (1).jar//org.geysermc.geyser.util.ItemUtils.getEnchantmentLevel(ItemUtils.java:62)
[09:12:55 WARN]:        at Geyser-Spigot (1).jar//org.geysermc.geyser.util.BlockUtils.getBreakTime(BlockUtils.java:148)
[09:12:55 WARN]:        at Geyser-Spigot (1).jar//org.geysermc.geyser.util.BlockUtils.getSessionBreakTime(BlockUtils.java:178)
[09:12:55 WARN]:        at Geyser-Spigot (1).jar//org.geysermc.geyser.translator.protocol.bedrock.entity.player.BedrockActionTranslator.translate(BedrockActionTranslator.java:214)
[09:12:55 WARN]:        at Geyser-Spigot (1).jar//org.geysermc.geyser.translator.protocol.bedrock.entity.player.BedrockActionTranslator.translate(BedrockActionTranslator.java:58)
[09:12:55 WARN]:        at Geyser-Spigot (1).jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89)
[09:12:55 WARN]:        at Geyser-Spigot (1).jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69)
[09:12:55 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[09:12:55 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[09:12:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[09:12:55 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[09:12:55 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[09:12:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[09:12:55 WARN]: [Geyser-Spigot] Could not translate packet PlayerActionPacket
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.item.enchantment.Enchantment.bedrockEnchantment()" because "enchantment" is null
        at Geyser-Spigot (1).jar/org.geysermc.geyser.util.ItemUtils.getEnchantmentLevel(ItemUtils.java:62) ~[Geyser-Spigot (1).jar:?]
        at Geyser-Spigot (1).jar/org.geysermc.geyser.util.BlockUtils.getBreakTime(BlockUtils.java:148) ~[Geyser-Spigot (1).jar:?]
        at Geyser-Spigot (1).jar/org.geysermc.geyser.util.BlockUtils.getSessionBreakTime(BlockUtils.java:178) ~[Geyser-Spigot (1).jar:?]
        at Geyser-Spigot (1).jar/org.geysermc.geyser.translator.protocol.bedrock.entity.player.BedrockActionTranslator.translate(BedrockActionTranslator.java:214) ~[Geyser-Spigot (1).jar:?]
        at Geyser-Spigot (1).jar/org.geysermc.geyser.translator.protocol.bedrock.entity.player.BedrockActionTranslator.translate(BedrockActionTranslator.java:58) ~[Geyser-Spigot (1).jar:?]
        at Geyser-Spigot (1).jar/org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[Geyser-Spigot (1).jar:?]
        at Geyser-Spigot (1).jar/org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[Geyser-Spigot (1).jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        
What does the plugin do with the enchantments?

**Comment by OmerBenGera** [comment]
The plugin does nothing with enchantments.
Contact Geyser regarding this, I dont think this is related to the plugin.
