### ISSUE TITLE
[Update] Support for Spigot / Paper version 1.21.1

### ISSUE THREAD

**Issue by RHX0R3** [BG-Software-LLC/WildLoaders#106]
### Minecraft's Version

Paper 1.21.1-5-master@7d7f123

### Plugin's Version

v2024.2

### Describe the bug

```
[02:31:04] [Server thread/INFO]: [WildLoaders] Loading server plugin WildLoaders v2024.2
[02:31:04] [Server thread/INFO]: [WildLoaders] &cThe plugin doesn't support your minecraft version.
[02:31:04] [Server thread/INFO]: [WildLoaders] &cPlease try a different version.
[02:31:04] [Server thread/WARN]: com.bgsoftware.wildloaders.libs.com.bgsoftware.common.nmsloader.NMSLoadException: Couldn't find valid builtin nms handlers for the data version: 3955
[02:31:04] [Server thread/WARN]: 	at WildLoaders-2024.2.jar//com.bgsoftware.wildloaders.libs.com.bgsoftware.common.nmsloader.NMSHandlersFactory.getNMSPackageVersionName(NMSHandlersFactory.java:70)
[02:31:04] [Server thread/WARN]: 	at WildLoaders-2024.2.jar//com.bgsoftware.wildloaders.libs.com.bgsoftware.common.nmsloader.NMSHandlersFactory.createNMSLoader(NMSHandlersFactory.java:26)
[02:31:04] [Server thread/WARN]: 	at WildLoaders-2024.2.jar//com.bgsoftware.wildloaders.WildLoadersPlugin.loadNMSAdapter(WildLoadersPlugin.java:104)
[02:31:04] [Server thread/WARN]: 	at WildLoaders-2024.2.jar//com.bgsoftware.wildloaders.WildLoadersPlugin.onLoad(WildLoadersPlugin.java:51)
[02:31:04] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[02:31:04] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[02:31:04] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[02:31:04] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
[02:31:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
[02:31:04] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
[02:31:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
[02:31:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[02:31:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[02:31:04] [Server thread/INFO]: [WildLoaders] &cThere was an error while loading the plugin.
```

### To Reproduce

Start with Spigot or Paper on 1.21.1

**Comment by andrewkm** [comment]
Not working on our end as well with Paper 1.21.1

**Comment by crumpkatrina** [comment]
Same issue happening here

**Comment by OmerBenGera** [comment]
Update to latest dev build, added support
