### ISSUE TITLE
Not keeping chunks loaded and no message above loader after server restart

### ISSUE THREAD

**Issue by NNickey** [BG-Software-LLC/WildLoaders#108]
### Minecraft's Version

Paper version 1.21.1-57-master@b483da4 (2024-09-01T18:09:05Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

WildLoaders-2024.3

### Describe the bug

Checking chunks loaded at spawn, other world currently has 251 chunks loaded via /uptime
Enter island world, place a loader with custom chunks-radius: 3
/uptime currently shows 1k+ chunks.
Leave island world, /uptime gradually goes to 251 chunks.

### To Reproduce

Place a loader
Switch worlds
/uptime shows no loader chunks

**Comment by OmerBenGera** [comment]
If no message is above the loader, I suspect there was an error or something and the loader was not properly been created.
Do you mind sending me your server logs, or look for errors yourself in the console?

**Comment by NNickey** [comment]
The message does appear above the loader when placed down, but when the server restarts, it doesn't reappear unless the loader is broken and placed down again.

It still seems to not keep chunks loaded, using /uptime and leaving the world shows the chunk count before the loader was placed.

Latest logs for wildloader has.

`[02:02:03] [ServerMain/INFO]: [PluginInitializerManager] Bukkit plugins (51):
 - AdvancedBan (2.3.0), AltDetector (2.03), AuctionMaster (4.1.3), AuraSkills (2.2.3), BlueSlimeCore (2.9.6.431), ChatGames (2.1.8), Citizens (2.0.35-SNAPSHOT (build 3545)), CyberLevels (0.5.9), DecentHolograms (2.8.11), DeluxeTags (1.8.2-Release), DropParty (1.0.1), Essentials (2.21.0-dev+111-b54c8c1), ExcellentCrates (5.3.1), FastAsyncWorldEdit (2.11.2-SNAPSHOT-894;4b099d3), FreedomChat (1.7.0), GadgetsMenu (4.15.2), GrimAC (2.3.66), HeadBlocks (2.5.6), Infiniteannouncements (2.4.1), ItemsAdder (4.0.2-beta-release-10), LPC (3.6.0), LoneLibs (1.0.58), LuckPerms (5.4.139), MiniMOTD (2.1.2), Multiverse-Core (4.3.12), Multiverse-Inventories (4.2.6), PlaceholderAPI (2.11.6), ProtocolLib (5.3.0-SNAPSHOT-726), Scale (1.0.1), SkBee (3.6.1), Skript (2.9.2), SuperiorSkyblock2 (2024.3), TAB (4.1.8), TCPShield (2.8.1), Tebex (2.0.6), ToastedAFK (2.0.2.2), TradeSystem (2.6.1), Vault (1.7.3-b131), ViaBackwards (5.0.3), ViaVersion (5.0.3), VotifierPlus (1.3), VotingPlugin (6.17.1), WildLoaders (2024.3), WildStacker (2024.3), WorldGuard (7.0.11-beta1+a801a9d), ajLeaderboards (2.9.0), nightcore (2.6.3), skRayFall (1.9.28), skript-gui (1.3), skript-placeholders (1.6.0), skript-reflect (2.5.1)
[02:12:23] [Server thread/INFO]: [WildLoaders] Enabling WildLoaders v2024.3
[02:12:23] [Server thread/INFO]: [WildLoaders] ******** ENABLE START ********
[02:12:23] [Server thread/INFO]: [WildLoaders] Loading configuration started...
[02:12:24] [Server thread/INFO]: [WildLoaders]  - Found 3 chunk-loaders in config.yml.
[02:12:24] [Server thread/INFO]: [WildLoaders] Loading configuration done (Took 12ms)
[02:12:24] [Server thread/INFO]: [WildLoaders] Loading messages started...
[02:12:24] [Server thread/INFO]: [WildLoaders]  - Found 25 messages in lang.yml.
[02:12:24] [Server thread/INFO]: [WildLoaders] Loading messages done (Took 3ms)
[02:12:24] [Server thread/INFO]: [WildLoaders] ******** ENABLE DONE ********

> server restart event
[19:43:20] [Server thread/INFO]: [WildLoaders] Disabling WildLoaders v2024.3
[19:43:20] [Server thread/ERROR]: Error occurred while disabling WildLoaders v2024.3
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.runDelayed(FoliaGlobalRegionScheduler.java:65) ~[paper-1.21.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.run(FoliaGlobalRegionScheduler.java:53) ~[paper-1.21.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FallbackRegionScheduler.run(FallbackRegionScheduler.java:18) ~[paper-1.21.1.jar:?]
	at WildLoaders-2024.3.jar/com.bgsoftware.wildloaders.scheduler.FoliaSchedulerImplementation.scheduleTask(FoliaSchedulerImplementation.java:28) ~[WildLoaders-2024.3.jar:?]
	at WildLoaders-2024.3.jar/com.bgsoftware.wildloaders.scheduler.Scheduler.runTask(Scheduler.java:40) ~[WildLoaders-2024.3.jar:?]
	at WildLoaders-2024.3.jar/com.bgsoftware.wildloaders.scheduler.Scheduler.runTask(Scheduler.java:68) ~[WildLoaders-2024.3.jar:?]
	at WildLoaders-2024.3.jar/com.bgsoftware.wildloaders.nms.v1_21.EntityHologram.removeHologram(EntityHologram.java:57) ~[WildLoaders-2024.3.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at WildLoaders-2024.3.jar/com.bgsoftware.wildloaders.nms.v1_21.NMSAdapterImpl.removeLoader(NMSAdapterImpl.java:137) ~[WildLoaders-2024.3.jar:?]
	at WildLoaders-2024.3.jar/com.bgsoftware.wildloaders.handlers.LoadersHandler.lambda$removeChunkLoaders$6(LoadersHandler.java:198) ~[WildLoaders-2024.3.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4783) ~[?:?]
	at WildLoaders-2024.3.jar/com.bgsoftware.wildloaders.handlers.LoadersHandler.removeChunkLoaders(LoadersHandler.java:198) ~[WildLoaders-2024.3.jar:?]
	at WildLoaders-2024.3.jar/com.bgsoftware.wildloaders.WildLoadersPlugin.onDisable(WildLoadersPlugin.java:98) ~[WildLoaders-2024.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:609) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1046) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:847) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

No other error message in console appears for WildLoaders when placing a loader down or leaving an area with a loader still in place.

**Comment by OmerBenGera** [comment]
Send me the error that you recieve when placing down chunk loaders

**Comment by NNickey** [comment]
I'm not receiving any errors when a chunk loader is placed down, and it shows the labels above the chunk loader and the timer counting down.

**Comment by NNickey** [comment]
Believe I found out the issue, the plugin wasn't relying on the chunks being loaded, instead relied on the players being in the server.

Closing, apologies.
