### ISSUE TITLE
Need help typing a command with an error

### ISSUE THREAD

**Issue by AllCheeks** [BG-Software-LLC/WildLoaders#109]
### Minecraft's Version

1.20.1

### Plugin's Version

2024.3

### Describe the bug

org.bukkit.command.CommandException: Cannot execute command 'wildloaders:loader' in plugin WildLoaders v2024.3-b34 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:38) ~[forge-1.20.1-47.3.11-universal.jar%23309!/:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[forge-1.20.1-47.3.11-universal.jar%23309!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:890) ~[forge-1.20.1-47.3.11-universal.jar%23309!/:997de31d-ddc9a2dad-d2eba2c8-47.1.106]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:51) ~[forge-1.20.1-47.3.11-universal.jar%23309!/:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.20.1.jar%23147!/:?]
        at net.minecraft.commands.Commands.m_242674_(Commands.java:321) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1872) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:1836) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:58) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1026) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:176) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1009) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1003) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:112) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:988) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:914) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

### To Reproduce

Enter /wildloaders:loader

**Comment by OmerBenGera** [comment]
The plugin does not support 1.20.1
Update to 1.20.4
