### ISSUE TITLE
BlockPlaceEvent error when placing beacon/loader

### ISSUE THREAD

**Issue by Virologicbody** [BG-Software-LLC/WildLoaders#20]
**Minecraft's Version**
Paper 1.17 Build 43 (latest as of this post)

**Plugin's Version**: -
Dev b-13

**Describe the bug**
Console error when placing beacon/loader

**To Reproduce**
Run Paper build 43 and WildLoaders dev version b-13.
Place beacon/loader

**Additional information**
Default configs

[21:52:02 ERROR]: Could not pass event BlockPlaceEvent to WildLoaders v1.0.0-DEVb13
java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.v1_17_R1.CraftServer net.minecraft.world.level.World.getServer()'
        at com.bgsoftware.wildloaders.nms.EntityHolograms_v1_17_R1.getBukkitEntity(EntityHolograms_v1_17_R1.java:164) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:705) ~[patched_1.17.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:629) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.server.level.ServerLevel.addEntity0(ServerLevel.java:1216) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1123) ~[?:?]
        at com.bgsoftware.wildloaders.nms.NMSAdapter_v1_17_R1$TileEntityChunkLoader.<init>(NMSAdapter_v1_17_R1.java:243) ~[?:?]
        at com.bgsoftware.wildloaders.nms.NMSAdapter_v1_17_R1.createLoader(NMSAdapter_v1_17_R1.java:135) ~[?:?]
        at com.bgsoftware.wildloaders.loaders.WChunkLoader.<init>(WChunkLoader.java:42) ~[?:?]
        at com.bgsoftware.wildloaders.handlers.LoadersHandler.addChunkLoader(LoadersHandler.java:75) ~[?:?]
        at com.bgsoftware.wildloaders.handlers.LoadersHandler.addChunkLoader(LoadersHandler.java:62) ~[?:?]
        at com.bgsoftware.wildloaders.listeners.BlocksListener.onLoaderPlace(BlocksListener.java:56) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-43]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-43]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-43]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:387) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.world.item.ItemStack.placeItem(ItemStack.java:374) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:571) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1743) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1340) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1273) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1184) ~[patched_1.17.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-43]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by OmerBenGera** [comment]
Fixed in latest dev build (14)
