### ISSUE TITLE
Error with EpicSpawners

### ISSUE THREAD

**Issue by paint2005** [BG-Software-LLC/WildLoaders#32]
### Minecraft's Version

paper 1.18.1 #132

### Plugin's Version

WildLoaders-1.0.3-b31 EpicSpawner 7.2.0

### Describe the bug

`[09:30:05 WARN]: [WildLoaders] Task #14 for WildLoaders v1.0.3.31 generated an exception
java.lang.NoClassDefFoundError: com/songoda/epicspawners/spawners/spawner/Spawner
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
        at java.lang.Class.getDeclaredMethod(Class.java:2673) ~[?:?]
        at com.bgsoftware.wildloaders.handlers.ProvidersHandler.createInstance(ProvidersHandler.java:90) ~[WildLoaders-1.0.3-b31.jar:?]
        at com.bgsoftware.wildloaders.handlers.ProvidersHandler.loadTickableProviders(ProvidersHandler.java:58) ~[WildLoaders-1.0.3-b31.jar:?]
        at com.bgsoftware.wildloaders.handlers.ProvidersHandler.lambda$new$0(ProvidersHandler.java:29) ~[WildLoaders-1.0.3-b31.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-132]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.songoda.epicspawners.spawners.spawner.Spawner
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 11 more`

### To Reproduce

Nothing special just installed the plugin and got this error on panel

**Comment by OmerBenGera** [comment]
Support for EpicSpawners 7 was added in latest dev build, which should fix the errors you had :)
