### ISSUE TITLE
Server crash after placing the chunkloader

### ISSUE THREAD

**Issue by NickHostingClub** [BG-Software-LLC/WildLoaders#69]
### Minecraft's Version

git-Paper-521 (MC: 1.19.4)

### Plugin's Version

Release 2023.1

### Describe the bug

Nothing special than just placing it and the server crashes.

### To Reproduce

So far only works when you place a block for the first time. After that you can pick it up and place it again. But it's just a normal beacon.

### Additional Information

[13:09:56 ERROR]: Could not pass event BlockPlaceEvent to WildLoaders v2023.1
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at com.bgsoftware.wildloaders.nms.v1194.NMSAdapter.createLoader(NMSAdapter.java:107) ~[WildLoaders-2023.1.jar:?]
        at com.bgsoftware.wildloaders.loaders.WChunkLoader.<init>(WChunkLoader.java:42) ~[WildLoaders-2023.1.jar:?]
        at com.bgsoftware.wildloaders.handlers.LoadersHandler.addChunkLoaderWithoutDBSave(LoadersHandler.java:77) ~[WildLoaders-2023.1.jar:?]
        at com.bgsoftware.wildloaders.handlers.LoadersHandler.addChunkLoader(LoadersHandler.java:63) ~[WildLoaders-2023.1.jar:?]
        at com.bgsoftware.wildloaders.listeners.BlocksListener.onLoaderPlace(BlocksListener.java:62) ~[WildLoaders-2023.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor298.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-538]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:415) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:408) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:598) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1959) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1428) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[13:09:56 ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at com.bgsoftware.wildloaders.nms.v1194.NMSAdapter.removeLoader(NMSAdapter.java:144) ~[WildLoaders-2023.1.jar:?]
        at com.bgsoftware.wildloaders.loaders.WChunkLoader.remove(WChunkLoader.java:108) ~[WildLoaders-2023.1.jar:?]
        at com.bgsoftware.wildloaders.nms.v1194.loader.ChunkLoaderBlockEntity.tick(ChunkLoaderBlockEntity.java:86) ~[WildLoaders-2023.1.jar:?]
        at com.bgsoftware.wildloaders.nms.v1194.loader.ChunkLoaderBlockEntityTicker.a(ChunkLoaderBlockEntityTicker.java:12) ~[WildLoaders-2023.1.jar:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:907) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:740) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1546) ~[paper-1.19.4.jar:git-Paper-538]
        ... 5 more
[13:09:56 ERROR]:       Cause of unexpected exception was
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at com.bgsoftware.wildloaders.nms.v1194.NMSAdapter.removeLoader(NMSAdapter.java:144) ~[WildLoaders-2023.1.jar:?]
        at com.bgsoftware.wildloaders.loaders.WChunkLoader.remove(WChunkLoader.java:108) ~[WildLoaders-2023.1.jar:?]
        at com.bgsoftware.wildloaders.nms.v1194.loader.ChunkLoaderBlockEntity.tick(ChunkLoaderBlockEntity.java:86) ~[WildLoaders-2023.1.jar:?]
        at com.bgsoftware.wildloaders.nms.v1194.loader.ChunkLoaderBlockEntityTicker.a(ChunkLoaderBlockEntityTicker.java:12) ~[WildLoaders-2023.1.jar:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:907) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:740) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1546) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by hendrikvalentim** [comment]
Just ran into what seems to be the same problem (no such mthod). Fresh server startup with WildLoaders-2023.1.jar for the first time. I gave myself a loader (from default config), then placed it down -> crash. Player is in the overall spawn area, in case that's relevant, but not inside spawn protection.

I'm attaching my crash report for completeness.
[crash-2023-05-21_16.54.11-server.txt](https://github.com/BG-Software-LLC/WildLoaders/files/11525098/crash-2023-05-21_16.54.11-server.txt)

**Comment by OmerBenGera** [comment]
Update to latest dev build.
