### ISSUE TITLE
Could not pass event BlockPlaceEvent to WildLoaders v2023.3

### ISSUE THREAD

**Issue by ricardo0115** [BG-Software-LLC/WildLoaders#77]
### Minecraft's Version

1.20.2 spigot-api-1.20.2-R0.1-SNAPSHOT.jar

### Plugin's Version

WildLoaders v2023.3

### Describe the bug

When placing a ChunkLoader block (large or normal) I have this exception on my server console.

`[14:45:53] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to WildLoaders v2023.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:451) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.world.item.ItemStack.a(ItemStack.java:366) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:559) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1549) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:32) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1133) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1112) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1105) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.util.thread.IAsyncTaskHandler.bp(SourceFile:115) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1088) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalAccessError: class com.bgsoftware.wildloaders.nms.v1_20_2.ChunkLoaderNPCImpl$DummyServerGamePacketListenerImpl tried to access private field net.minecraft.world.entity.player.EntityHuman.cr (com.bgsoftware.wildloaders.nms.v1_20_2.ChunkLoaderNPCImpl$DummyServerGamePacketListenerImpl is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @73dd5605; net.minecraft.world.entity.player.EntityHuman is in unnamed module of loader java.net.URLClassLoader @5b80350b)
	at com.bgsoftware.wildloaders.nms.v1_20_2.ChunkLoaderNPCImpl$DummyServerGamePacketListenerImpl.<init>(ChunkLoaderNPCImpl.java:139) ~[?:?]
	at com.bgsoftware.wildloaders.nms.v1_20_2.ChunkLoaderNPCImpl.<init>(ChunkLoaderNPCImpl.java:62) ~[?:?]
	at com.bgsoftware.wildloaders.nms.v1_20_2.NMSAdapter.createNPC(NMSAdapter.java:88) ~[?:?]
	at com.bgsoftware.wildloaders.handlers.NPCHandler.lambda$createNPC$0(NPCHandler.java:37) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at com.bgsoftware.wildloaders.handlers.NPCHandler.createNPC(NPCHandler.java:37) ~[?:?]
	at com.bgsoftware.wildloaders.handlers.LoadersHandler.addChunkLoaderWithoutDBSave(LoadersHandler.java:82) ~[?:?]
	at com.bgsoftware.wildloaders.handlers.LoadersHandler.addChunkLoader(LoadersHandler.java:63) ~[?:?]
	at com.bgsoftware.wildloaders.listeners.BlocksListener.onLoaderPlace(BlocksListener.java:62) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	... 23 more`

### To Reproduce

This exception is raised when a chunk loader block is placed

**Comment by ricardo0115** [comment]
Hello, I tried the lastest dev build of the plugin (#7 05/10/2023 14:31:49), I have this error on Spigot server
``
[18:24:30] [Server thread/INFO]: [WildLoaders] Enabling WildLoaders v2023.3-b7
[18:24:30] [Server thread/INFO]: [WildLoaders] ******** ENABLE START ********
[18:24:30] [Server thread/INFO]: [WildLoaders] Loading configuration started...
[18:24:30] [Server thread/ERROR]: Error occurred while enabling WildLoaders v2023.3-b7 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.bgsoftware.wildloaders.nms.NMSAdapter.setTag(org.bukkit.inventory.ItemStack, String, String)" because the return value of "com.bgsoftware.wildloaders.WildLoadersPlugin.getNMSAdapter()" is null
	at com.bgsoftware.wildloaders.loaders.WLoaderData.<init>(WLoaderData.java:26) ~[?:?]
	at com.bgsoftware.wildloaders.handlers.LoadersHandler.createLoaderData(LoadersHandler.java:102) ~[?:?]
	at com.bgsoftware.wildloaders.handlers.SettingsHandler.<init>(SettingsHandler.java:91) ~[?:?]
	at com.bgsoftware.wildloaders.WildLoadersPlugin.onEnable(WildLoadersPlugin.java:71) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3877-Spigot-17ca32d-f070277]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
``
However the plugin works on Paper version git-Paper-223 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: a702a08)


Thanks for help !

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by SkyKingPX** [comment]
Same. In the Dev Build 5 the commands work, but not the ChunkLoader. And in the 7. dev build its not even enabling. 

Also using Spigot 1.20.2

**Comment by Radjak** [comment]
Same error on Spigot 1.20.2

I can use the command to get block but the block don't work (same error stack as above).

**Comment by OmerBenGera** [comment]
Check out latest dev build, hopefully it will work now

**Comment by Radjak** [comment]
Yes ! The dev build 8 is working ! Congrats & thanks !

**Comment by brianholle** [comment]
@OmerBenGera Issue appeared again on spigot v1.20.4 on latest dev build (12). 

`Could not pass event BlockPlaceEvent to WildLoaders`

**Comment by brianholle** [comment]
Further info about the error, looks like a null exception.
https://gist.github.com/brianholle/1cd3e19350e2ed5d28793f8f6bb83788

**Comment by OmerBenGera** [comment]
> Further info about the error, looks like a null exception. https://gist.github.com/brianholle/1cd3e19350e2ed5d28793f8f6bb83788

Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs let me know
