### ISSUE TITLE
Error using /loader give

### ISSUE THREAD

**Issue by HeroLeam** [BG-Software-LLC/WildLoaders#90]
### Minecraft's Version

1.20.4

### Plugin's Version

WildLoaders-2023.3

### Describe the bug

[21:02:17] [Server thread/WARN]: Unexpected exception while parsing console command "loader giver heroleam chunk 1h"
org.bukkit.command.CommandException: Cannot execute command 'loader' in plugin WildLoaders v2023.3 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:875) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3979-Spigot-06d602e-f03fc3a]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:860) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3979-Spigot-06d602e-f03fc3a]
        at net.minecraft.server.dedicated.DedicatedServer.bk(DedicatedServer.java:412) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3979-Spigot-06d602e-f03fc3a]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3979-Spigot-06d602e-f03fc3a]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1248) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3979-Spigot-06d602e-f03fc3a]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1054) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3979-Spigot-06d602e-f03fc3a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3979-Spigot-06d602e-f03fc3a]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### To Reproduce

/loader giver heroleam chunk 1h

**Comment by OmerBenGera** [comment]
The plugin is not enabled.
This is because you use the stable version on 1.20.4. Update to latest dev build.

**Comment by HeroLeam** [comment]
> The plugin is not enabled. This is because you use the stable version on 1.20.4. Update to latest dev build.

It's just that https://bg-software.com/wildloaders says 1.20.X so you understand that they are all subsequent versions...
![image](https://github.com/BG-Software-LLC/WildLoaders/assets/92167805/acb24f60-481f-43b0-a0ee-7802036f87ea)
