### ISSUE TITLE
Plugin not works

### ISSUE THREAD

**Issue by Envqu** [BG-Software-LLC/WildLoaders#97]
### Minecraft's Version

Purpur-2176 1.20.4

### Plugin's Version

v2024.1-b23

### Describe the bug

[17:09:31] [Server thread/INFO]: [WildLoaders] Enabling WildLoaders v2024.1-b23
[17:09:31] [Server thread/INFO]: [WildLoaders] ******** ENABLE START ********
[17:09:31] [Server thread/ERROR]: Error occurred while enabling WildLoaders v2024.1-b23 (Is it up to date?)
java.lang.NoClassDefFoundError: com/grinderwolf/swm/api/world/properties/SlimePropertyMap
	at com.bgsoftware.wildloaders.hooks.WorldsProvider_SlimeWorldManager.<clinit>(WorldsProvider_SlimeWorldManager.java:18) ~[WildLoaders-2024.1-b23.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:421) ~[?:?]
	at java.lang.Class.forName(Class.java:412) ~[?:?]
	at com.bgsoftware.wildloaders.handlers.ProvidersHandler.createInstance(ProvidersHandler.java:145) ~[WildLoaders-2024.1-b23.jar:?]
	at com.bgsoftware.wildloaders.handlers.ProvidersHandler.loadWorldProviders(ProvidersHandler.java:94) ~[WildLoaders-2024.1-b23.jar:?]
	at com.bgsoftware.wildloaders.handlers.ProvidersHandler.<init>(ProvidersHandler.java:33) ~[WildLoaders-2024.1-b23.jar:?]
	at com.bgsoftware.wildloaders.WildLoadersPlugin.onEnable(WildLoadersPlugin.java:70) ~[WildLoaders-2024.1-b23.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.grinderwolf.swm.api.world.properties.SlimePropertyMap
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 20 more
[17:09:31] [Server thread/INFO]: [WildLoaders] Disabling WildLoaders v2024.1-b23

### To Reproduce

.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Envqu** [comment]
Thanks for fast reply.
I have one more question. Can you add HEX support (Item Name/Lore & Hologram) for WildLoaders like in SuperiorSkyBlock2 in close future?

**Comment by OmerBenGera** [comment]
You can use hex in any plugin. Use `&x` as a prefix, then the hex value, where each char has a `&` before it.
For example, for the color #123456, use `&x&1&2&3&4&5&6`
